#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
app_lucky_number:
    path: /admin_page
    controller: App\Controller\AdminPageController::page
